### PR TITLE
Bug fixes for term datasource

### LINKED ISSUE #386: Unit tests fail after r34737
As Travis has noted, Fieldmanager's unit tests are failing after [r34737](https://core.trac.wordpress.org/changeset/34737) in core -- specifically, [`test_datasource_term_save_empty()`](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/tests/php/test-fieldmanager-datasource-term.php#L194), `Failed asserting that null is identical to ''`.

It looks like we need to investigate whether this change poses a larger problem for how FM manages data than updating the types in that one test.

### PR DESCRIPTION
**Pull request by mboynes**
* Fix a data type issue introduced in core, because `null !== ''` (see #386 for further details; this resolves #386)
* Ensure any taxonomy used in a datasource, where the data is stored as a term relationship, is sortable

### CODE REVIEW

File: php/datasource/class-fieldmanager-datasource-term.php [hunk 1]
```diff
@@ -76,15 +76,20 @@ public function __construct( $options = array() ) {
...
+		// Ensure that $taxonomy_save_to_terms is true if it needs to be
+		if ( $this->only_save_to_taxonomy ) {
+			$this->taxonomy_save_to_terms = true;
 		}
-		if ( $this->only_save_to_taxonomy && in_array( 'category', $this->get_taxonomies() ) ) {
-			$wp_taxonomies['category']->sort = True;
+
+		if ( $this->taxonomy_save_to_terms ) {
+			// Ensure that the taxonomies are sortable if we're not using FM
+			// storage
```
Comment (dlh01) [inline php/datasource/class-fieldmanager-datasource-term.php]: Odd-looking widow on this line.

Also, core standards suggest sentences in docs are supposed to end with...eh, never mind.

File: php/datasource/class-fieldmanager-datasource-term.php [hunk 2]
```diff
@@ -76,15 +76,20 @@ public function __construct( $options = array() ) {
...
+			foreach ( $this->get_taxonomies() as $taxonomy ) {
+				if ( ! empty( $wp_taxonomies[ $taxonomy ] ) ) {
```
Comment (dlh01) [inline php/datasource/class-fieldmanager-datasource-term.php]: Although they're functionally the same thing, would it be preferable to use `taxonomy_exists()`?

**Comment by dlh01** [comment]
Two minor comments, otherwise looks :deciduous_tree: to me.

File: php/datasource/class-fieldmanager-datasource-term.php (hunk 2 above)
Comment (mboynes) [inline php/datasource/class-fieldmanager-datasource-term.php]: We're already using `$wp_taxonomies`, so we may as well save the function call IMO
